---
title             : "The title of my manuscript"
shorttitle        : "this brilliant work...."
author: 
  - name          : "Joe Bloggs"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Department of Psychology, The Best University, UK"
    email         : "j.bloggs@best.psych.ac.uk"
  - name          : "David Smith" 
    affiliation   : "2"
affiliation:
  - id            : "1"
    institution   : "Best University, UK"
  - id            : "2"
    institution   : "Better University, Spain"
abstract: |
  abstract here
  
  
  
  Public significance statement: 
keywords          : "keywords"
wordcount         : "X"
bibliography      : ["references.bib"]
figsintext        : yes
floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no
header-includes:
  - \raggedbottom
  - \usepackage[font={small,it}, labelfont={bf}]{caption}
csl               : "apa7.csl"
documentclass     : "apa7"
classoption       : "man"
output            : papaja::apa6_pdf
editor_options: 
  chunk_output_type: console
---

```{r knitr-options}
knitr::opts_chunk$set(warning=FALSE, 
                      message=FALSE, 
                      include=FALSE,
                      dev = "cairo_pdf")
```

```{r rmd-setup, include = FALSE}
library(tidyverse)
library(citr)
library(papaja)
library(english)
library(extrafont)
library(BayesFactor)


# function used to set rounding and presentation of decimals to specific length
spec_dec <- function(x, k) trimws(format(round(x, k), nsmall=k)) # useful for controlling decimals

# function to force scientific formatting of numbers (used for large BFs)
changeSciNot <- function(n) {
  output <- format(n, scientific = TRUE, digits = 2) #Transforms the number into scientific notation even if small
  output <- sub("e", "x10^", output) #Replace e with 10^
  output <- sub("\\+0?", "", output) #Remove + symbol and leading zeros on expoent, if > 1
  output <- sub("-0?", "-", output) #Leaves - symbol but removes leading zeros on expoent, if < 1
  output
}


```

Intro text here [@shanks1985]

# Experiment 1

This is going to be a great experiment

## Method

### Participants

Some brains were collected

### Materials

The stuff was like this

### Design

We did some stuff

### Procedure

They did some stuff

## Results


```{r BF_example}



data(sleep)
plot(extra ~ group, data = sleep)

## traditional ANOVA gives a p value of 0.00283
summary(aov(extra ~ group + Error(ID/group), data = sleep))

## Gives a Bayes factor of about 11.6
## in favor of the alternative hypothesis
resultBF <- 
  anovaBF(extra ~ group + ID, 
          data = sleep, 
          whichRandom = "ID")




```

BF~10~ `r extractBF(resultBF)$bf` &plusmn; `r round(100*extractBF(resultBF)$error,2)`%.

## Discussion

Wow what a great result

\newpage

# References
